/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List clusters in the caller's tenant. */
        get: operations["listClusters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listScans"];
        put?: never;
        /** Trigger an on-demand scan (analyst+). */
        post: operations["triggerScan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Server-side filtered/sorted/paginated findings. */
        get: operations["listFindings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/posture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPosture"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/attack-paths": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAttackPaths"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Server-Sent Events — scan progress and posture updates. */
        get: operations["stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
        };
        /** @enum {string} */
        Severity: "critical" | "high" | "medium" | "low" | "info";
        Cluster: {
            id: string;
            name: string;
            environment?: string;
            lastScanAt?: string;
            totalFindings?: number;
            overallPassRate?: number;
        };
        ClusterList: {
            clusters: components["schemas"]["Cluster"][];
        };
        Scan: {
            id: string;
            clusterId: string;
            /** @enum {string} */
            status: "queued" | "running" | "succeeded" | "failed";
            startedAt?: string;
            finishedAt?: string;
            totalFindings?: number;
        };
        ScanList: {
            scans: components["schemas"]["Scan"][];
            total: number;
        };
        TriggerScanRequest: {
            clusterId: string;
        };
        ResourceRef: {
            kind: string;
            namespace?: string;
            name: string;
        };
        ControlRef: {
            framework: string;
            id: string;
            title?: string;
        };
        Evidence: {
            path: string;
            /** @description redacted where sensitive — key name only */
            value?: string;
        };
        Remediation: {
            summary: string;
            snippet?: string;
        };
        Finding: {
            id: string;
            title: string;
            severity: components["schemas"]["Severity"];
            category: string;
            resource: components["schemas"]["ResourceRef"];
            evidence?: components["schemas"]["Evidence"][];
            remediation: components["schemas"]["Remediation"];
            grants?: string[];
            refs?: components["schemas"]["ControlRef"][];
        };
        FindingPage: {
            findings: components["schemas"]["Finding"][];
            total: number;
            limit: number;
            offset: number;
        };
        PostureSummary: {
            totalFindings: number;
            bySeverity: {
                [key: string]: number;
            };
            criticalPaths: number;
            controlsAssessed: number;
            controlsBreached: number;
            overallPassRate: number;
        };
        ControlBreach: {
            controlId: string;
            title?: string;
            findings: string[];
        };
        FrameworkResult: {
            framework: string;
            version?: string;
            assessed: number;
            breached: number;
            passed: number;
            passRate: number;
            breaches?: components["schemas"]["ControlBreach"][];
            disclaimer: string;
        };
        PostureResponse: {
            posture: components["schemas"]["PostureSummary"];
            compliance: components["schemas"]["FrameworkResult"][];
        };
        PathHop: {
            order: number;
            from: string;
            to: string;
            enabledBy: string;
            technique: string[];
            narrative: string;
        };
        AttackPath: {
            id: string;
            title: string;
            severity: components["schemas"]["Severity"];
            entry: components["schemas"]["ResourceRef"];
            hops: components["schemas"]["PathHop"][];
            summary: string;
        };
        AttackPathList: {
            paths: components["schemas"]["AttackPath"][];
        };
        HistorySnapshot: {
            scanId: string;
            at: string;
            totalFindings: number;
            controlsAssessed: number;
            controlsBreached: number;
            overallPassRate: number;
            bySeverity: {
                [key: string]: number;
            };
        };
        HistoryList: {
            snapshots: components["schemas"]["HistorySnapshot"][];
        };
        StreamEvent: {
            /** @enum {string} */
            type: "scan_started" | "scan_progress" | "scan_completed" | "posture_updated";
            clusterId?: string;
            scanId?: string;
            progress?: number;
            message?: string;
        };
    };
    responses: {
        /** @description insufficient role */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listClusters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description clusters */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterList"];
                };
            };
        };
    };
    listScans: {
        parameters: {
            query?: {
                cluster?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description scans */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanList"];
                };
            };
        };
    };
    triggerScan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TriggerScanRequest"];
            };
        };
        responses: {
            /** @description accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scan"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    listFindings: {
        parameters: {
            query?: {
                cluster?: string;
                severity?: string;
                category?: string;
                framework?: string;
                namespace?: string;
                search?: string;
                sort?: string;
                order?: "asc" | "desc";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description findings page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingPage"];
                };
            };
        };
    };
    getPosture: {
        parameters: {
            query?: {
                cluster?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description posture + per-framework compliance */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostureResponse"];
                };
            };
        };
    };
    listAttackPaths: {
        parameters: {
            query?: {
                cluster?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description attack paths */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttackPathList"];
                };
            };
        };
    };
    getHistory: {
        parameters: {
            query?: {
                cluster?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description history snapshots (oldest first) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryList"];
                };
            };
        };
    };
    stream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description text/event-stream of StreamEvent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["StreamEvent"];
                };
            };
        };
    };
}
