{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kubeguard.fullname" . }}
  labels:
    {{- include "kubeguard.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kubeguard.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
